# Generated by Django 3.0.2 on 2020-05-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spansalon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
    ]
