# Generated by Django 3.0.2 on 2020-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spansalon', '0002_remove_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phonenum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
